Clean up FIFA Goals data
source file: data cleaning\fifa goals\fifa-worldcup-goals-cleanup.xlsx

In [18]:
import pandas as pd

df = pd.read_excel(r"fifa-worldcup-goals-cleanup.xlsx")
df

,Date,Home Goals,Away Goals,Home Country,Away Country
0,"June 11, 2026 (2026-06-11)1:00 p.m. UTC−6",Quiñones 9'\nJiménez 67',NaN,Mexico,South Africa
1,"June 11, 2026 (2026-06-11)8:00 p.m. UTC−6",Hwang In-beom 67'\nOh Hyeon-gyu 80',Krejčí 59',South Korea,Czech Republic
2,"June 12, 2026 (2026-06-12)3:00 p.m. UTC−4",Larin 78',Lukić 21',Canada,Bosnia and Herzegovina
3,"June 13, 2026 (2026-06-13)12:00 p.m. UTC−7",Muheim 90+4' (o.g.),Embolo 17' (pen.),Qatar,Switzerland
4,"June 13, 2026 (2026-06-13)6:00 p.m. UTC−4",Vinícius 32',Saibari 21',Brazil,Morocco
5,"June 13, 2026 (2026-06-13)9:00 p.m. UTC−4",NaN,McGinn 28',Haiti,Scotland
6,"June 12, 2026 (2026-06-12)6:00 p.m. UTC−7","Bobadilla 7' (o.g.)\nBalogun 31', 45+5'\nRey...",Maurício 73',United States,Paraguay
7,"June 13, 2026 (2026-06-13)9:00 p.m. UTC−7",Irankunda 27'\nMetcalfe 75',NaN,Australia,Turkey
8,"June 14, 2026 (2026-06-14)12:00 p.m. UTC−5",Nmecha 6'\nSchlotterbeck 38'\nHavertz 45+5'...,Comenencia 21',Germany,Curaçao
9,"June 14, 2026 (2026-06-14)7:00 p.m. UTC−4",Diallo 90',NaN,Ivory Coast,Ecuador
10,"June 14, 2026 (2026-06-14)3:00 p.m. UTC−5",Van Dijk 50'\nSummerville 64',Nakamura 57'\nKamada 88',Netherlands,Japan
11,"June 14, 2026 (2026-06-14)8:00 p.m. UTC−6","Ayari 7', 90+6'\nIsak 30'\nGyökeres 59'\nSv...",Rekik 43',Sweden,Tunisia
12,"June 15, 2026 (2026-06-15)12:00 p.m. UTC−7",Hany 66' (o.g.),Ashour 19',Belgium,Egypt
13,"June 15, 2026 (2026-06-15)6:00 p.m. UTC−7",Rezaeian 32'\nMohebi 64',"Just 7', 54'",Iran,New Zealand
14,"June 15, 2026 (2026-06-15)6:00 p.m. UTC−4",Al-Amri 41',M. Araújo 80',Saudi Arabia,Uruguay
15,"June 16, 2026 (2026-06-16)3:00 p.m. UTC−4","Mbappé 66', 90+6'\nBarcola 82'",Mbaye 90+5',France,Senegal
16,"June 16, 2026 (2026-06-16)6:00 p.m. UTC−4",Hussein 39',"Haaland 29', 43'\nØstigård 76'\nHussein 90+...",Iraq,Norway
17,"June 16, 2026 (2026-06-16)8:00 p.m. UTC−5","Messi 17', 60', 76'",NaN,Argentina,Algeria
18,"June 16, 2026 (2026-06-16)9:00 p.m. UTC−7",Schmid 20'\nAl-Arab 76' (o.g.)\nArnautović ...,Olwan 50',Austria,Jordan
19,"June 17, 2026 (2026-06-17)12:00 p.m. UTC−5",J. Neves 6',Wissa 45+5',Portugal,DR Congo
20,"June 17, 2026 (2026-06-17)3:00 p.m. UTC−5","Kane 12' (pen.), 42'\nBellingham 47'\nRashfo...",Baturina 36'\nMusa 45+5',England,Croatia

Lets combine all goals to a 3 column table - date, country, goal detail

In [19]:
df_home = df[['Date','Home Goals','Home Country']]
df_away = df[['Date','Away Goals','Away Country']]
df_home.columns = ['Date', 'Goal Detail','Country']
df_away.columns = df_home.columns
df_all  = pd.concat([df_home, df_away])
df_all = df_all.dropna()
df_all

,Date,Goal Detail,Country
0,"June 11, 2026 (2026-06-11)1:00 p.m. UTC−6",Quiñones 9'\nJiménez 67',Mexico
1,"June 11, 2026 (2026-06-11)8:00 p.m. UTC−6",Hwang In-beom 67'\nOh Hyeon-gyu 80',South Korea
2,"June 12, 2026 (2026-06-12)3:00 p.m. UTC−4",Larin 78',Canada
3,"June 13, 2026 (2026-06-13)12:00 p.m. UTC−7",Muheim 90+4' (o.g.),Qatar
4,"June 13, 2026 (2026-06-13)6:00 p.m. UTC−4",Vinícius 32',Brazil
6,"June 12, 2026 (2026-06-12)6:00 p.m. UTC−7","Bobadilla 7' (o.g.)\nBalogun 31', 45+5'\nRey...",United States
7,"June 13, 2026 (2026-06-13)9:00 p.m. UTC−7",Irankunda 27'\nMetcalfe 75',Australia
8,"June 14, 2026 (2026-06-14)12:00 p.m. UTC−5",Nmecha 6'\nSchlotterbeck 38'\nHavertz 45+5'...,Germany
9,"June 14, 2026 (2026-06-14)7:00 p.m. UTC−4",Diallo 90',Ivory Coast
10,"June 14, 2026 (2026-06-14)3:00 p.m. UTC−5",Van Dijk 50'\nSummerville 64',Netherlands
11,"June 14, 2026 (2026-06-14)8:00 p.m. UTC−6","Ayari 7', 90+6'\nIsak 30'\nGyökeres 59'\nSv...",Sweden
12,"June 15, 2026 (2026-06-15)12:00 p.m. UTC−7",Hany 66' (o.g.),Belgium
13,"June 15, 2026 (2026-06-15)6:00 p.m. UTC−7",Rezaeian 32'\nMohebi 64',Iran
14,"June 15, 2026 (2026-06-15)6:00 p.m. UTC−4",Al-Amri 41',Saudi Arabia
15,"June 16, 2026 (2026-06-16)3:00 p.m. UTC−4","Mbappé 66', 90+6'\nBarcola 82'",France
16,"June 16, 2026 (2026-06-16)6:00 p.m. UTC−4",Hussein 39',Iraq
17,"June 16, 2026 (2026-06-16)8:00 p.m. UTC−5","Messi 17', 60', 76'",Argentina
18,"June 16, 2026 (2026-06-16)9:00 p.m. UTC−7",Schmid 20'\nAl-Arab 76' (o.g.)\nArnautović ...,Austria
19,"June 17, 2026 (2026-06-17)12:00 p.m. UTC−5",J. Neves 6',Portugal
20,"June 17, 2026 (2026-06-17)3:00 p.m. UTC−5","Kane 12' (pen.), 42'\nBellingham 47'\nRashfo...",England
1,"June 11, 2026 (2026-06-11)8:00 p.m. UTC−6",Krejčí 59',Czech Republic
2,"June 12, 2026 (2026-06-12)3:00 p.m. UTC−4",Lukić 21',Bosnia and Herzegovina
3,"June 13, 2026 (2026-06-13)12:00 p.m. UTC−7",Embolo 17' (pen.),Switzerland
4,"June 13, 2026 (2026-06-13)6:00 p.m. UTC−4",Saibari 21',Morocco
5,"June 13, 2026 (2026-06-13)9:00 p.m. UTC−4",McGinn 28',Scotland
6,"June 12, 2026 (2026-06-12)6:00 p.m. UTC−7",Maurício 73',Paraguay
8,"June 14, 2026 (2026-06-14)12:00 p.m. UTC−5",Comenencia 21',Curaçao
10,"June 14, 2026 (2026-06-14)3:00 p.m. UTC−5",Nakamura 57'\nKamada 88',Japan
11,"June 14, 2026 (2026-06-14)8:00 p.m. UTC−6",Rekik 43',Tunisia
12,"June 15, 2026 (2026-06-15)12:00 p.m. UTC−7",Ashour 19',Egypt
13,"June 15, 2026 (2026-06-15)6:00 p.m. UTC−7","Just 7', 54'",New Zealand
14,"June 15, 2026 (2026-06-15)6:00 p.m. UTC−4",M. Araújo 80',Uruguay
15,"June 16, 2026 (2026-06-16)3:00 p.m. UTC−4",Mbaye 90+5',Senegal
16,"June 16, 2026 (2026-06-16)6:00 p.m. UTC−4","Haaland 29', 43'\nØstigård 76'\nHussein 90+...",Norway
18,"June 16, 2026 (2026-06-16)9:00 p.m. UTC−7",Olwan 50',Jordan
19,"June 17, 2026 (2026-06-17)12:00 p.m. UTC−5",Wissa 45+5',DR Congo
20,"June 17, 2026 (2026-06-17)3:00 p.m. UTC−5",Baturina 36'\nMusa 45+5',Croatia

Let's split the goals by new line

In [20]:
df_all['Goals'] = df_all['Goal Detail'].str.split('\n')
df_all = df_all.explode('Goals')
df_all

,Date,Goal Detail,Country,Goals
0,"June 11, 2026 (2026-06-11)1:00 p.m. UTC−6",Quiñones 9'\nJiménez 67',Mexico,Quiñones 9'
0,"June 11, 2026 (2026-06-11)1:00 p.m. UTC−6",Quiñones 9'\nJiménez 67',Mexico,Jiménez 67'
1,"June 11, 2026 (2026-06-11)8:00 p.m. UTC−6",Hwang In-beom 67'\nOh Hyeon-gyu 80',South Korea,Hwang In-beom 67'
1,"June 11, 2026 (2026-06-11)8:00 p.m. UTC−6",Hwang In-beom 67'\nOh Hyeon-gyu 80',South Korea,Oh Hyeon-gyu 80'
2,"June 12, 2026 (2026-06-12)3:00 p.m. UTC−4",Larin 78',Canada,Larin 78'
...,...,...,...,...
16,"June 16, 2026 (2026-06-16)6:00 p.m. UTC−4","Haaland 29', 43'\nØstigård 76'\nHussein 90+...",Norway,Hussein 90+6' (o.g.)
18,"June 16, 2026 (2026-06-16)9:00 p.m. UTC−7",Olwan 50',Jordan,Olwan 50'
19,"June 17, 2026 (2026-06-17)12:00 p.m. UTC−5",Wissa 45+5',DR Congo,Wissa 45+5'
20,"June 17, 2026 (2026-06-17)3:00 p.m. UTC−5",Baturina 36'\nMusa 45+5',Croatia,Baturina 36'
20,"June 17, 2026 (2026-06-17)3:00 p.m. UTC−5",Baturina 36'\nMusa 45+5',Croatia,Musa 45+5'

Let's split the goal times and explode them as well

In [21]:
df_all[['Player', 'Minutes Raw']] = df_all['Goals'].str.split(r"(?=\d)", n=1, expand=True)
df_all['Minute'] = df_all['Minutes Raw'].str.split(",")
df_all = df_all.explode('Minute').reset_index(drop=True)
df_all["Player"] = df_all["Player"].str.strip()
df_all["Minute"] = df_all["Minute"].str.strip()
df_all

,Date,Goal Detail,Country,Goals,Player,Minutes Raw,Minute
0,"June 11, 2026 (2026-06-11)1:00 p.m. UTC−6",Quiñones 9'\nJiménez 67',Mexico,Quiñones 9',Quiñones,9',9'
1,"June 11, 2026 (2026-06-11)1:00 p.m. UTC−6",Quiñones 9'\nJiménez 67',Mexico,Jiménez 67',Jiménez,67',67'
2,"June 11, 2026 (2026-06-11)8:00 p.m. UTC−6",Hwang In-beom 67'\nOh Hyeon-gyu 80',South Korea,Hwang In-beom 67',Hwang In-beom,67',67'
3,"June 11, 2026 (2026-06-11)8:00 p.m. UTC−6",Hwang In-beom 67'\nOh Hyeon-gyu 80',South Korea,Oh Hyeon-gyu 80',Oh Hyeon-gyu,80',80'
4,"June 12, 2026 (2026-06-12)3:00 p.m. UTC−4",Larin 78',Canada,Larin 78',Larin,78',78'
...,...,...,...,...,...,...,...
65,"June 16, 2026 (2026-06-16)6:00 p.m. UTC−4","Haaland 29', 43'\nØstigård 76'\nHussein 90+...",Norway,Hussein 90+6' (o.g.),Hussein,90+6' (o.g.),90+6' (o.g.)
66,"June 16, 2026 (2026-06-16)9:00 p.m. UTC−7",Olwan 50',Jordan,Olwan 50',Olwan,50',50'
67,"June 17, 2026 (2026-06-17)12:00 p.m. UTC−5",Wissa 45+5',DR Congo,Wissa 45+5',Wissa,45+5',45+5'
68,"June 17, 2026 (2026-06-17)3:00 p.m. UTC−5",Baturina 36'\nMusa 45+5',Croatia,Baturina 36',Baturina,36',36'
69,"June 17, 2026 (2026-06-17)3:00 p.m. UTC−5",Baturina 36'\nMusa 45+5',Croatia,Musa 45+5',Musa,45+5',45+5'

Let's remove the columns we no longer need and 
clean up OG & Pen stuff and add them as a column to tag the goal

In [22]:
import numpy as np

goal_checks = [
    df_all['Minute'].str.contains('(o.g.)',regex=False, na=False),
    df_all['Minute'].str.contains('(pen.)', regex=False, na=False),
]
goal_types = ['Own Goal', 'Penalty']

df_all = df_all[['Date','Country','Player','Minute']].copy()
df_all['Goal Type'] = np.select(goal_checks, goal_types, default="Regular")
df_all

,Date,Country,Player,Minute,Goal Type
0,"June 11, 2026 (2026-06-11)1:00 p.m. UTC−6",Mexico,Quiñones,9',Regular
1,"June 11, 2026 (2026-06-11)1:00 p.m. UTC−6",Mexico,Jiménez,67',Regular
2,"June 11, 2026 (2026-06-11)8:00 p.m. UTC−6",South Korea,Hwang In-beom,67',Regular
3,"June 11, 2026 (2026-06-11)8:00 p.m. UTC−6",South Korea,Oh Hyeon-gyu,80',Regular
4,"June 12, 2026 (2026-06-12)3:00 p.m. UTC−4",Canada,Larin,78',Regular
...,...,...,...,...,...
65,"June 16, 2026 (2026-06-16)6:00 p.m. UTC−4",Norway,Hussein,90+6' (o.g.),Own Goal
66,"June 16, 2026 (2026-06-16)9:00 p.m. UTC−7",Jordan,Olwan,50',Regular
67,"June 17, 2026 (2026-06-17)12:00 p.m. UTC−5",DR Congo,Wissa,45+5',Regular
68,"June 17, 2026 (2026-06-17)3:00 p.m. UTC−5",Croatia,Baturina,36',Regular
69,"June 17, 2026 (2026-06-17)3:00 p.m. UTC−5",Croatia,Musa,45+5',Regular